include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

# custom_lint:
#   debug: true
#   verbose: true
# Configuração opcional para tornar presentation_no_data um ERROR
# custom_lint:
#   rules:
#     - presentation_no_data:
#         severity: error
