include:
  - package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    clean_arch_lint:
      paths: /Users/saulogatti-pessoal/Public/DocumentosLocal/repo/flutter_arq_lint/clean_archt_lint
      diagnostics:
        presentation_no_data: true
        teste_meu: true
